title: My Super Awesome Title
author: GitHub User
email: your-email@domain.com
description: > MY DESCRIPTION IS NOT EMPTY MOTHER FUCKER

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
