title: My new awesome title
author: JohnnySanderss
email: 
description: This is my NEW updated description for my side

# social links
twitter_username: 
github_username:  JohnnySanderss

show_excerpts: false
