title: My Super Awesome Title
author: JohnnySanderss
description:  |
    Follow the Yellow Brick
    
    Road!
theme: minima

# social links
discord_username: JohnnySanderss#9655
# email: your-email@example.com
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  johnnysanderss 

show_excerpts: false # set to false to remove excerpts on the homepage
