title: My Super Awesome Title
author: GitHub User
email: your-email@domain.com
description:  >
    Follow the Yellow Brick
    Road to the Emerald City.
    Pay no attention to the
    man behind 
    the 
    curtain.
theme: minima

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  johnnysanderss 

show_excerpts: true # set to false to remove excerpts on the homepage
